# Generated by Django 3.2 on 2021-07-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_add_auto_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='thumbnail_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
