# Generated by Django 3.2 on 2021-07-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='info_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
