# Generated by Django 3.2 on 2022-03-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0008_add_ownedbook_review_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="thumbnail_height",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="book",
            name="thumbnail_width",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
