# Generated by Django 3.2 on 2025-08-21 15:00

from django.db import migrations, models


# add RunPython to initialize progress field based on read attribute


def initialize_progress(apps, schema_editor):
    OwnedBook = apps.get_model('books', 'OwnedBook')
    for owned_book in OwnedBook.objects.all():
        if owned_book.read:
            owned_book.progress = "fully_read"
            owned_book.save(update_fields=['progress'])


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_add_book_thumbnail_width_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownedbook',
            name='progress',
            field=models.CharField(choices=[('unread', 'Unread'), ('partially_read', 'Partially Read'), ('fully_read', 'Fully Read')], default='unread', max_length=24),
        ),
        migrations.RunPython(
            code=initialize_progress,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='ownedbook',
            name='read',
        ),
    ]
